/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leapfrog.crud.ui;

import com.leapfrog.crud.dao.CourseDAO;
import com.leapfrog.crud.dao.impl.CourseDAOImpl;
import com.leapfrog.crud.entity.Course;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author HP B&O
 */
public class CourseUI extends javax.swing.JFrame {

    private CourseDAO courseDAO = new CourseDAOImpl();

    /**
     * Creates new form CourseUI
     */
    public CourseUI() {
        initComponents();
        loadTable();
    }

    public void loadTable() {
        try {
            String[] columns = {"Id", "Name", "Fees", "Added Date", "Status"};
            tblCourse.setModel(new CourseTableModel(columns, courseDAO.getAll()));
        } catch (ClassNotFoundException | SQLException se) {
            JOptionPane.showMessageDialog(null, se.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public CourseDAO getCourseDAO() {
        return courseDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(tblCourse);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leapfrog/crud/resources/add.png"))); // NOI18N
        btnAdd.setText(" Add Course");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonClick(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leapfrog/crud/resources/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnClick(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leapfrog/crud/resources/delete.png"))); // NOI18N
        btnDelete.setText("Remove");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnClick(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnDelete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonClick
        // TODO add your handling code here:
        AddCourseUI addCourseUI = new AddCourseUI(this, true);
        addCourseUI.setVisible(true);
    }//GEN-LAST:event_addCourseButtonClick

    private void closeBtnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnClick
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeBtnClick

    private void deleteBtnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnClick
        // TODO add your handling code here:
        int row = tblCourse.getSelectedRow();
        if (row < 1) {
            JOptionPane.showMessageDialog(null, "Recors not selected.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int id = (int) tblCourse.getValueAt(row, 0);
                int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Confirm Delete?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.OK_OPTION) {
                    courseDAO.delete(id);
                    loadTable();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBtnClick

    private class CourseTableModel extends AbstractTableModel {

        private List<Course> courseList;
        private String[] columns;

        public CourseTableModel(String[] columns, List<Course> courseList) {
            this.columns = columns;
            this.courseList = courseList;
        }

        @Override
        public int getRowCount() {
            return courseList.size();
        }

        @Override
        public int getColumnCount() {
            return columns.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Course course = courseList.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return course.getId();
                case 1:
                    return course.getName();
                case 2:
                    return course.getFees();
                case 3:
                    return course.getAddedDate();
                case 4:
                    return course.isStatus();
            }
            return null;
        }

        @Override
        public String getColumnName(int column) {
            return columns[column];
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourse;
    // End of variables declaration//GEN-END:variables
}
